### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by bajibabu** [dagbldr/dagbldr#121]
Hi,

I got the following error when I tried to run the "datasets/preprocessing_utils.py" file.
Traceback (most recent call last):
  File "preprocessing_utils.py", line 849, in <module>
    f_hz, m = sinusoid_analysis(X, input_sample_rate=16000)
  File "preprocessing_utils.py", line 427, in sinusoid_analysis
    window_size=2 \* step_size)
  File "preprocessing_utils.py", line 171, in lpc_analysis
    n_windows = n_points // window_step
ZeroDivisionError: float divmod()

That is a "ZeroDivisionError". I figured out that "window_step" value is 0. So, I modified the line 423 in  "datasets/preprocessing_utils.py" file. 

step_size = 2 \* round(float(resample_block) / input_sample_rate \* resample_to / 2.)
step_size = int(step_size)

**Comment by kastnerkyle** [comment]
I think I know the fix for this - will update it in some coming weeks.

**Comment by kastnerkyle** [comment]
Sorry for the slow reply - I think this is fixed now. I had a bug in overlap/add that should be resolved now. I also fixed in my audio_tools.py gist, which largely is the same as this.

**Comment by bajibabu** [comment]
Thank you!
